global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #    monitor: 'S&P Monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  - "alert.rules.WIN"

## A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
#    static_configs:
#      - targets: ['192.168.1.92:9100']

#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['cadvisor:8080']

#  - job_name: 'prometheus'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['localhost:9090']

#  - job_name: 'pushgateway'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['pushgateway:9091']

#  - job_name: 'exporter'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['exporter:5002']

#  - job_name: 'Rasberry4'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['192.168.1.36:9100']
#        labels:
#          env: "RASBERRYS"
#          so: "LINUX"
#          type: "SO"
#          network: "192.168.0/24"
#          funcion: "Pentesting"


#  - job_name: 'Rasberry3'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['192.168.1.26:9100']
#        labels:
#          env: "RASBERRYS"
#          so: "LINUX"
#          type: "SO"
#          network: "192.168.0/24"
#          funcion: "Pentesting"

  - job_name: 'infosec'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.24:9100']
        labels:
          env: "PORTATIL"
          so: "LINUX"
          type: "LINUX"
          network: "192.168.0/24"
          funcion: "Pentesting"

#  - job_name: 'ASUS-LAPTOP'
#    scrape_interval: 10s
#    honor_labels: true
#    static_configs:
#      - targets: ['192.168.1.31:9182']
#        labels:   
#          env: "PORTATIL"
#          so: "WINDOWS"
#          type: "SO"
#          network: "192.168.0/24"
#          funcion: "Trabajo"

# SERVER PROXMOX Y CLUSTERS

  - job_name: 'SRV-PROXMOX'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.39:9100']
        labels:
          env: "SERVIDOR"
          so: "LINUX"
          type: "SO"
          network: "192.168.0/24"
          funcion: "VM & DOCKERS"

  - job_name: 'DOCK4-ADGUARD'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.154:9100']
        labels:
          env: "SERVIDOR"
          so: "LINUX"
          type: "VM"
          network: "monitor-net"
          funcion: "Network Monitor"

  - job_name: 'DOCK1-PROMETHEUS-LOKI-GRAFANA'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.41:9100']
        labels:
          env: "SERVIDOR"
          so: "LINUX"
          type: "DOCKER"
          network: "loki"
          funcion: "Metricas & Logs"

  - job_name: 'DOCK2--TERRAFORM'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.152:9100']
        labels:
          env: "SERVIDOR"
          so: "LINUX"
          type: "DOCKER"
          network: "192.168.1.0"
          funcion: "Terraform"

  - job_name: 'DOCK3-TOR'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.153:9100']
        labels:
          env: "SERVIDOR"
          so: "LINUX"
          type: "DOCKER"
          network: "192.168.1.0"
          funcion: "PROXY-TOR"

  - job_name: 'DOCKER-CINE-SERIES'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['192.168.1.107:9100']
        labels:
          env: "SERVIDOR"
          so: "LINUX"
          type: "DOCKER"
          network: "192.168.1.0"
          funcion: "PROXY-TOR"


#  - job_name: 'DOCK4-InfoSecInstitute2'
#    scrape_interval: 10s
